#!/usr/bin/env bash
range="127.0.0.1"
dir="${HOME}/.nmapdiff"
d="${dir}/scan_$(date +%Y-%m-%d).txt"
y="${dir}/scan_$(date -d yesterday +Y-%m-%d).txt"

if [ ! -d "${dir}" ]; then
    mkdir -v "${dir}"
fi

if ! [ -x "$(command -v nmap)" ]; then
    echo 'nmap is not installed.' >&2
    exit 1
fi

nmap -A -T4 -sV -sT --top-ports 200 -Pn --script vuln -oN "${d}" "${range}" > /dev/null 2>&1

if [ -e "${y}" ]; then
    diff "${y}" "${d}" > "${dir}"/diff.txt
fi


