#!/usr/bin/env bash
range="127.0.0.1"
dir="${HOME}/.nmapdiff"
today="${dir}/scan_$(date +%Y-%m-%d).txt"
yesterday="${dir}/scan_$(date -d yesterday +Y-%m-%d).txt"

if [ ! -d "${dir}" ]; then
    mkdir -v "${dir}"
fi

if ! [ -x "$(command -v nmap)" ]; then
    echo 'nmap is not installed.' >&2
    exit 1
fi

echo "nmap -A -T4 -sV -sT --top-ports 200 -Pn --script vuln -oN "${today}" "${range}" > /dev/null 2>&1"
nmap -A -T4 -sV -sT --top-ports 200 -Pn --script vuln -oN "${today}" "${range}" > /dev/null 2>&1

if [ -e "${yesterday}" ]; then
    diff "${yesterday}" "${today}" > "${dir}"/diff.txt
fi


